---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

stages:
  - commit
  - syntax
  - docker

# commit
git-history:
  stage: commit
  script:
    - >
      bash <(curl --fail --location --silent --show-error
      https://git.io/vxIxF)

lines-length:
  stage: commit
  script:
    - >
      bash <(curl --fail --location --silent --show-error
      https://git.io/vxIxN)

# syntax
docker-lint:
  stage: syntax
  image: vpgrp/linter:docker
  script:
    - find . -type f -name "Dockerfile" | xargs -I{} dockerlint {}

# docker
build-latest:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm --tag vpgrp/nodejs:latest .

build-4:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm --tag vpgrp/nodejs:4 4

build-5:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm --tag vpgrp/nodejs:5 5

build-6:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm --tag vpgrp/nodejs:6 6

build-7:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm --tag vpgrp/nodejs:7 7

build-8:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm --tag vpgrp/nodejs:8 8

build-9:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm --tag vpgrp/nodejs:9 9
# EOF
